### ISSUE TITLE
Забил ли ты на проект?

### ISSUE THREAD

**Issue by Snoweeew** [thedeaddan/autobuy_minecraft#6]
Если нет - ответь, пожалуйста. Могу помочь с дальнейшей доработкой

**Comment by thedeaddan** [comment]
Ну я его больше не использую, если есть доработки, то кидай пулл реквест, гляну

**Comment by Roma97791** [comment]
Привет, при запуске такая ошибка ModuleNotFoundError: No module named 'win32gui' может дело в том что у меня 64разрядная windows 

И если что библеатеку я устанавливал разными способами

**Comment by thedeaddan** [comment]
> Привет, при запуске такая ошибка ModuleNotFoundError: No module named 'win32gui' может дело в том что у меня 64разрядная windows
> 
> И если что библеатеку я устанавливал разными способами

Ради тебя сейчас обновлю код и описание)

**Comment by thedeaddan** [comment]
> Привет, при запуске такая ошибка ModuleNotFoundError: No module named 'win32gui' может дело в том что у меня 64разрядная windows
> 
> И если что библеатеку я устанавливал разными способами

Возможно библиотеки уже не актуальны, но должно сработать
```sh
pip install win32gui
```

**Comment by Roma97791** [comment]
Спасибо :)
